# Generated by Django 3.1.3 on 2020-11-15 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('company_institution', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('is_student', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[(0, 'credit card'), (1, 'cash'), (2, 'check')], max_length=100)),
                ('current_balance', models.IntegerField()),
                ('transaction_date_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date_time', models.DateTimeField()),
                ('end_date_time', models.DateTimeField()),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_of_registrants', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(choices=[], max_length=50)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('session_type', models.CharField(choices=[(2, 'workshop'), (1, 'tutorial'), (0, 'technical')], max_length=10)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deadline', models.DateField()),
                ('number_of_speakers', models.IntegerField()),
                ('number_of_registrants', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Speaks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.attendee')),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.session')),
            ],
        ),
        migrations.CreateModel(
            name='Registered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.attendee')),
                ('conference_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.conference')),
                ('material_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.materials')),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.session')),
            ],
        ),
        migrations.CreateModel(
            name='Has_Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.attendee')),
                ('bill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.bill')),
            ],
        ),
        migrations.CreateModel(
            name='Has_Available',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conference_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.conference')),
                ('material_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.materials')),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.session')),
            ],
        ),
    ]
