# Generated by Django 3.1.3 on 2020-11-17 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference_Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Purchased_Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date_time', models.DateTimeField()),
                ('attendee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.attendee')),
            ],
        ),
        migrations.CreateModel(
            name='Purchased_Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date_time', models.DateTimeField()),
                ('attendee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.attendee')),
            ],
        ),
        migrations.RemoveField(
            model_name='has_bill',
            name='attendee_id',
        ),
        migrations.RemoveField(
            model_name='has_bill',
            name='bill_id',
        ),
        migrations.RemoveField(
            model_name='registered',
            name='attendee_id',
        ),
        migrations.RemoveField(
            model_name='registered',
            name='conference_id',
        ),
        migrations.RemoveField(
            model_name='registered',
            name='material_id',
        ),
        migrations.RemoveField(
            model_name='registered',
            name='session_id',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='deadline',
            new_name='discount_deadline',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='transaction_date_time',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='end_date_time',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='start_date_time',
        ),
        migrations.AddField(
            model_name='bill',
            name='attendee_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='conferences.attendee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materials',
            name='conference_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='conferences.conference'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='conference_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='conferences.conference'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='materials',
            name='material_type',
            field=models.CharField(choices=[(0, 'banquet ticket'), (1, 'proceedings')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Has_Available',
        ),
        migrations.DeleteModel(
            name='Has_Bill',
        ),
        migrations.DeleteModel(
            name='Registered',
        ),
        migrations.AddField(
            model_name='purchased_session',
            name='session_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.session'),
        ),
        migrations.AddField(
            model_name='purchased_material',
            name='material_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.materials'),
        ),
        migrations.AddField(
            model_name='conference_date',
            name='conference_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.conference'),
        ),
    ]
