# Generated by Django 3.1.3 on 2020-11-17 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0002_auto_20201117_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='number_of_registrants',
            field=models.IntegerField(default=0),
        ),
    ]
