# Generated by Django 3.1.3 on 2020-11-18 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0004_auto_20201117_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
