# Generated by Django 3.1.3 on 2020-11-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0006_auto_20201117_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='attendee_id',
            new_name='attendee',
        ),
        migrations.RenameField(
            model_name='conference_date',
            old_name='conference_id',
            new_name='conference',
        ),
        migrations.RenameField(
            model_name='materials',
            old_name='conference_id',
            new_name='conference',
        ),
        migrations.RenameField(
            model_name='purchased_material',
            old_name='attendee_id',
            new_name='attendee',
        ),
        migrations.RenameField(
            model_name='purchased_material',
            old_name='material_id',
            new_name='material',
        ),
        migrations.RenameField(
            model_name='purchased_session',
            old_name='attendee_id',
            new_name='attendee',
        ),
        migrations.RenameField(
            model_name='purchased_session',
            old_name='session_id',
            new_name='session',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='conference_id',
            new_name='conference',
        ),
        migrations.RenameField(
            model_name='speaks',
            old_name='attendee_id',
            new_name='attendee',
        ),
        migrations.RenameField(
            model_name='speaks',
            old_name='session_id',
            new_name='session',
        ),
        migrations.AlterField(
            model_name='bill',
            name='payment_type',
            field=models.CharField(choices=[('Credit Card', 'Credit Card'), ('Cash', 'Cash'), ('Check', 'Check')], default='Credit Card', max_length=11),
        ),
        migrations.AlterField(
            model_name='materials',
            name='material_type',
            field=models.CharField(choices=[('Banquet Tickets', 'Banquet Tickets'), ('Proceedings', 'Proceedings')], default='Banquet Tickets', max_length=15),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_type',
            field=models.CharField(choices=[('Workshop', 'Workshop'), ('Tutorial', 'Tutorial'), ('Technical', 'Technical')], default='Technical', max_length=9),
        ),
    ]
