# Generated by Django 3.1.3 on 2020-11-18 22:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0009_auto_20201118_1626'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conference_date_time',
            options={'verbose_name': 'Conference Date Time'},
        ),
        migrations.AlterField(
            model_name='conference_date_time',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 18, 16, 39, 30, 946710)),
        ),
        migrations.AlterField(
            model_name='purchased_material',
            name='transaction_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 18, 16, 39, 30, 949710)),
        ),
        migrations.AlterField(
            model_name='purchased_session',
            name='transaction_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 18, 16, 39, 30, 948710)),
        ),
    ]
