# Generated by Django 3.1.3 on 2020-11-19 19:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0010_auto_20201118_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materials',
            name='amount',
        ),
        migrations.AlterField(
            model_name='conference_date_time',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 19, 13, 13, 27, 659206)),
        ),
        migrations.AlterField(
            model_name='purchased_material',
            name='transaction_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 19, 13, 13, 27, 661206)),
        ),
        migrations.AlterField(
            model_name='purchased_session',
            name='transaction_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 19, 13, 13, 27, 660206)),
        ),
    ]
