# Generated by Django 3.1.3 on 2020-11-19 19:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0012_auto_20201119_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference_date_time',
            name='end_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 19, 13, 50, 57, 421315)),
        ),
        migrations.AlterField(
            model_name='conference_date_time',
            name='start_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 19, 13, 50, 57, 421315)),
        ),
        migrations.AlterField(
            model_name='purchased_material',
            name='transaction_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 19, 13, 50, 57, 423312)),
        ),
        migrations.AlterField(
            model_name='purchased_session',
            name='transaction_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 19, 13, 50, 57, 423312)),
        ),
    ]
