# Generated by Django 3.1.3 on 2020-11-19 21:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0013_auto_20201119_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchased_Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proceedings_amt', models.IntegerField(default=0)),
                ('banquet_tickets_amt', models.IntegerField(default=1)),
                ('is_tutorial_purchased', models.BooleanField(default=False)),
                ('is_workshop_purchased', models.BooleanField(default=False)),
                ('payment_type', models.CharField(choices=[('Credit Card', 'Credit Card'), ('Cash', 'Cash'), ('Check', 'Check')], default='Credit Card', max_length=11)),
                ('transaction_date_time', models.DateTimeField(default=datetime.datetime(2020, 11, 19, 15, 23, 24, 114574))),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.attendee')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.conference')),
            ],
        ),
        migrations.RemoveField(
            model_name='purchased_session',
            name='attendee',
        ),
        migrations.RemoveField(
            model_name='purchased_session',
            name='session',
        ),
        migrations.AlterField(
            model_name='conference_date_time',
            name='end_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 19, 15, 23, 24, 112510)),
        ),
        migrations.AlterField(
            model_name='conference_date_time',
            name='start_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 19, 15, 23, 24, 112510)),
        ),
        migrations.DeleteModel(
            name='Purchased_Material',
        ),
        migrations.DeleteModel(
            name='Purchased_Session',
        ),
    ]
