# Generated by Django 3.1.3 on 2020-11-19 23:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0015_auto_20201119_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference_date_time',
            name='end_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 19, 17, 34, 27, 761250)),
        ),
        migrations.AlterField(
            model_name='conference_date_time',
            name='start_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 19, 17, 34, 27, 761250)),
        ),
        migrations.AlterField(
            model_name='purchased_conference',
            name='transaction_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 19, 17, 34, 27, 762264)),
        ),
    ]
