# Generated by Django 3.1.3 on 2020-11-21 07:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0017_auto_20201119_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference_date_time',
            name='end_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 1, 27, 2, 558315)),
        ),
        migrations.AlterField(
            model_name='conference_date_time',
            name='start_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 1, 27, 2, 558315)),
        ),
        migrations.AlterField(
            model_name='purchased_conference',
            name='banquet_tickets_amt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchased_conference',
            name='transaction_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 1, 27, 2, 560315)),
        ),
    ]
