# Generated by Django 3.1.3 on 2020-11-21 19:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0018_auto_20201121_0127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conference_date_time',
            options={},
        ),
        migrations.AlterField(
            model_name='conference_date_time',
            name='end_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 13, 45, 12, 142313)),
        ),
        migrations.AlterField(
            model_name='conference_date_time',
            name='start_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 13, 45, 12, 142313)),
        ),
        migrations.AlterField(
            model_name='purchased_conference',
            name='transaction_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 13, 45, 12, 143313)),
        ),
    ]
