# Generated by Django 3.1.3 on 2020-11-21 21:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0021_auto_20201121_1515'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchased_conference',
            options={'verbose_name_plural': 'Purchased Conferences'},
        ),
        migrations.AlterField(
            model_name='conference_date_time',
            name='end_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 15, 34, 5, 489652)),
        ),
        migrations.AlterField(
            model_name='conference_date_time',
            name='start_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 15, 34, 5, 489652)),
        ),
        migrations.AlterField(
            model_name='purchased_conference',
            name='transaction_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 15, 34, 5, 491651)),
        ),
    ]
